theme: jekyll-theme-minimal
title: "AdA Project"
description: "Research group “Audio-visual rhetorics of affect” - FU Berlin + HPI Potsdam"

navigation:
  - title: "Home"
    url: /
  - title: "About the Project"
    url: /about/
  - title: "AdA Filmontology"
    url: /ontology/
  - title: "Corpus Metadata"
    url: /corpus/
  - title: "Film-Analytical Annotations"
    url: /annotations/
  - title: "Publications"
    url: /publications/
  - title: "Quick Links"
    subitems:
      - title: "- GitHub Repository"
        url: https://github.com/ProjectAdA/public
      - title: "- AdA @ FU Berlin"
        url: https://www.ada.cinepoetics.fu-berlin.de/en/index.html
      - title: "- Advene Website"
        url: https://www.advene.org/
      - title: "- OntoViz"
        url: https://ada.cinepoetics.org/ontoviz/
      - title: "- Corpus Overview"
        url: https://ada.cinepoetics.org/corpus/
      - title: "- Annotation Explorer"
        url: https://ada.cinepoetics.org/explorer/

markdown: kramdown

author:
  name: Henning Agt-Rickauer
